### ISSUE TITLE
hust slack community

### ISSUE THREAD

**Issue by shahzebsiddiqui** [hust-workshop/hust-workshop.github.io#1]
Hello Chris and @gonsie  

It would be nice to get a slack channel for hust to help with communication and letting folks join the channel to build the community. Let me know your thoughts, if you agree I am happy to set that up for you guys.

**Comment by gonsie** [comment]
@shahzabsiddiqui that would be wonderful! Please set it up and I’ll post the information to our website / in the readme

**Comment by shahzebsiddiqui** [comment]
@gonsie 

slack site is created can you try this heroku link https://hust-invite-slack.herokuapp.com/ that will do the authentication to the slack channel. Type your email and heroku will send you an email confirmation. Once you confirm it should allow you to access slack.

The slack channel is called https://hpcusersupporttools.slack.com

**Comment by gonsie** [comment]
Yay, thank you!
